"""add rental budget and rent split fields

Revision ID: 12a773e7a9fd
Revises: 6af8c2d6e43d
Create Date: 2026-07-28 17:48:09.445539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a773e7a9fd'
down_revision: Union[str, Sequence[str], None] = '6af8c2d6e43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('total_monthly_rent', sa.Integer(), nullable=True))
    op.add_column('community_members', sa.Column('monthly_contribution', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('rental_budget', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rental_budget')
    op.drop_column('community_members', 'monthly_contribution')
    op.drop_column('communities', 'total_monthly_rent')
    # ### end Alembic commands ###
