"""add solvency passports table

Revision ID: 238f173a7fd3
Revises: 785f4fbdd7cd
Create Date: 2026-08-03 15:20:36.044651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '238f173a7fd3'
down_revision: Union[str, Sequence[str], None] = '785f4fbdd7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solvency_passports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_analysis_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('share_nonce', sa.String(length=64), nullable=False),
    sa.Column('share_token_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'EXPIRED', 'REVOKED', name='solvency_passport_status'), nullable=False),
    sa.Column('algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('analysis_period_start', sa.Date(), nullable=True),
    sa.Column('analysis_period_end', sa.Date(), nullable=True),
    sa.Column('months_analyzed', sa.Integer(), nullable=False),
    sa.Column('recurring_monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_fixed_expenses', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_variable_expenses', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_monthly_margin', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recommended_rent_capacity', sa.Numeric(precision=12, scale=2), nullable=True),
    # income_stability y analysis_confidence ya existen (creados por la
    # migración de financial_analyses); create_type=False evita que
    # Alembic intente recrearlos y falle con "type already exists".
    sa.Column(
        'income_stability',
        postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='income_stability', create_type=False),
        nullable=False,
    ),
    sa.Column(
        'confidence_level',
        postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='analysis_confidence', create_type=False),
        nullable=False,
    ),
    sa.Column('holder_initials', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['financial_analysis_id'], ['financial_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_solvency_passports_financial_analysis_id'), 'solvency_passports', ['financial_analysis_id'], unique=False)
    op.create_index(op.f('ix_solvency_passports_user_id'), 'solvency_passports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solvency_passports_user_id'), table_name='solvency_passports')
    op.drop_index(op.f('ix_solvency_passports_financial_analysis_id'), table_name='solvency_passports')
    op.drop_table('solvency_passports')
    # Solo el enum creado por ESTA migración. income_stability y
    # analysis_confidence son reutilizados por financial_analyses y no
    # deben borrarse aquí.
    sa.Enum(name='solvency_passport_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
