"""add onboarding profile

Revision ID: 7841b5c5b746
Revises: ab8c331e4220
Create Date: 2026-07-27 19:43:58.098272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7841b5c5b746'
down_revision: Union[str, Sequence[str], None] = 'ab8c331e4220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compatibility_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cleanliness', sa.String(), nullable=False),
    sa.Column('dishes', sa.String(), nullable=False),
    sa.Column('common_objects', sa.String(), nullable=False),
    sa.Column('noise', sa.String(), nullable=False),
    sa.Column('visits', sa.String(), nullable=False),
    sa.Column('sleepovers', sa.String(), nullable=False),
    sa.Column('wake_up', sa.String(), nullable=False),
    sa.Column('night_noise', sa.String(), nullable=False),
    sa.Column('smoking', sa.String(), nullable=False),
    sa.Column('alcohol', sa.String(), nullable=False),
    sa.Column('pets', sa.String(), nullable=False),
    sa.Column('bills', sa.String(), nullable=False),
    sa.Column('food', sa.String(), nullable=False),
    sa.Column('communication', sa.String(), nullable=False),
    sa.Column('conflicts', sa.String(), nullable=False),
    sa.Column('rules', sa.String(), nullable=False),
    sa.Column('culture', sa.String(), nullable=False),
    sa.Column('space', sa.String(), nullable=False),
    sa.Column('lifestyle', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column(
        'users',
        sa.Column(
            'onboarding_completed',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )
    op.alter_column('users', 'onboarding_completed', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_table('compatibility_profiles')
    # ### end Alembic commands ###
