"""add financial analysis tables

Revision ID: 785f4fbdd7cd
Revises: dbaa071a74a6
Create Date: 2026-08-02 17:03:37.987588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785f4fbdd7cd'
down_revision: Union[str, Sequence[str], None] = 'dbaa071a74a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_connection_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'COMPLETED', 'INSUFFICIENT_DATA', 'FAILED', 'OUTDATED', name='financial_analysis_status'), nullable=False),
    sa.Column('algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('analysis_period_start', sa.Date(), nullable=True),
    sa.Column('analysis_period_end', sa.Date(), nullable=True),
    sa.Column('months_analyzed', sa.Integer(), nullable=False),
    sa.Column('accounts_analyzed', sa.Integer(), nullable=False),
    sa.Column('transactions_analyzed', sa.Integer(), nullable=False),
    sa.Column('average_monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('median_monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recurring_monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_monthly_fixed_expenses', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_monthly_variable_expenses', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_monthly_outflows', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_monthly_net_margin', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('minimum_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('months_with_negative_balance', sa.Integer(), nullable=False),
    sa.Column('income_stability', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='income_stability'), nullable=True),
    sa.Column('analysis_confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='analysis_confidence'), nullable=True),
    sa.Column('recommended_monthly_rent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_quality_score', sa.Integer(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_connection_id'], ['bank_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_analyses_bank_connection_id'), 'financial_analyses', ['bank_connection_id'], unique=False)
    op.create_index(op.f('ix_financial_analyses_user_id'), 'financial_analyses', ['user_id'], unique=False)
    op.create_table('financial_monthly_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_analysis_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recurring_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_fixed_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_variable_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_outflows', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_margin', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('income_sources_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['financial_analysis_id'], ['financial_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_analysis_id', 'year', 'month', name='uq_financial_monthly_summary_analysis_year_month')
    )
    op.create_index(op.f('ix_financial_monthly_summaries_financial_analysis_id'), 'financial_monthly_summaries', ['financial_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_monthly_summaries_financial_analysis_id'), table_name='financial_monthly_summaries')
    op.drop_table('financial_monthly_summaries')
    op.drop_index(op.f('ix_financial_analyses_user_id'), table_name='financial_analyses')
    op.drop_index(op.f('ix_financial_analyses_bank_connection_id'), table_name='financial_analyses')
    op.drop_table('financial_analyses')
    sa.Enum(name='analysis_confidence').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='income_stability').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='financial_analysis_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
