"""add community join type

Revision ID: 991d97e1eb2f
Revises: 9d60e3f1972e
Create Date: 2026-07-28 00:52:01.299017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991d97e1eb2f'
down_revision: Union[str, Sequence[str], None] = '9d60e3f1972e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    join_type_enum = sa.Enum(
        'OPEN', 'REQUEST', name='community_join_type'
    )
    join_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'communities',
        sa.Column(
            'join_type',
            join_type_enum,
            nullable=False,
            server_default='REQUEST'
        )
    )
    op.alter_column('communities', 'join_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'join_type')

    sa.Enum(name='community_join_type').drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
