"""add community preferences

Revision ID: 9d60e3f1972e
Revises: b7cf09539ff4
Create Date: 2026-07-27 21:07:01.137676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d60e3f1972e'
down_revision: Union[str, Sequence[str], None] = 'b7cf09539ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('cleanliness', sa.String(length=150), nullable=False),
    sa.Column('atmosphere', sa.String(length=150), nullable=False),
    sa.Column('visits', sa.String(length=150), nullable=False),
    sa.Column('sleepovers', sa.String(length=150), nullable=False),
    sa.Column('smoking', sa.String(length=150), nullable=False),
    sa.Column('pets', sa.String(length=150), nullable=False),
    sa.Column('rules', sa.String(length=150), nullable=False),
    sa.Column('lifestyle', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_preferences_community_id'), 'community_preferences', ['community_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_preferences_community_id'), table_name='community_preferences')
    op.drop_table('community_preferences')
    # ### end Alembic commands ###
