"""add invitations applications saved profiles connections private messages notifications

Revision ID: b0824d3c7f7d
Revises: 12a773e7a9fd
Create Date: 2026-07-28 18:26:02.241678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0824d3c7f7d'
down_revision: Union[str, Sequence[str], None] = '12a773e7a9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('COMMUNITY_APPLICATION_RECEIVED', 'COMMUNITY_APPLICATION_ACCEPTED', 'COMMUNITY_APPLICATION_REJECTED', 'COMMUNITY_INVITATION_ACCEPTED', 'CONNECTION_REQUEST_RECEIVED', 'CONNECTION_REQUEST_ACCEPTED', 'COMMUNITY_MEMBER_JOINED', 'COMMUNITY_MEMBER_LEFT', 'PRIVATE_MESSAGE_RECEIVED', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('saved_user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('saved_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['saved_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'saved_user_id', name='uq_saved_user_profiles_user_saved_user')
    )
    op.create_index(op.f('ix_saved_user_profiles_saved_user_id'), 'saved_user_profiles', ['saved_user_id'], unique=False)
    op.create_index(op.f('ix_saved_user_profiles_user_id'), 'saved_user_profiles', ['user_id'], unique=False)
    op.create_table('user_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='user_connection_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_connections_recipient_id'), 'user_connections', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_user_connections_requester_id'), 'user_connections', ['requester_id'], unique=False)
    op.create_table('community_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='community_application_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_applications_applicant_id'), 'community_applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_community_applications_community_id'), 'community_applications', ['community_id'], unique=False)
    op.create_index('uq_community_applications_pending', 'community_applications', ['community_id', 'applicant_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('community_invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', 'EXPIRED', name='community_invitation_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_invitations_community_id'), 'community_invitations', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_invitations_token'), 'community_invitations', ['token'], unique=True)
    op.create_table('private_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['user_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_messages_connection_id'), 'private_messages', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_private_messages_connection_id'), table_name='private_messages')
    op.drop_table('private_messages')
    op.drop_index(op.f('ix_community_invitations_token'), table_name='community_invitations')
    op.drop_index(op.f('ix_community_invitations_community_id'), table_name='community_invitations')
    op.drop_table('community_invitations')
    op.drop_index('uq_community_applications_pending', table_name='community_applications', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_community_applications_community_id'), table_name='community_applications')
    op.drop_index(op.f('ix_community_applications_applicant_id'), table_name='community_applications')
    op.drop_table('community_applications')
    op.drop_index(op.f('ix_user_connections_requester_id'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_recipient_id'), table_name='user_connections')
    op.drop_table('user_connections')
    op.drop_index(op.f('ix_saved_user_profiles_user_id'), table_name='saved_user_profiles')
    op.drop_index(op.f('ix_saved_user_profiles_saved_user_id'), table_name='saved_user_profiles')
    op.drop_table('saved_user_profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###

    sa.Enum(name='notification_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='community_invitation_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='community_application_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_connection_status').drop(op.get_bind(), checkfirst=True)
