"""add bank connection truelayer tables

Revision ID: dbaa071a74a6
Revises: e7c3a5f81b4d
Create Date: 2026-08-02 14:15:51.396249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaa071a74a6'
down_revision: Union[str, Sequence[str], None] = 'e7c3a5f81b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_auth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_auth_states_state_hash'), 'bank_auth_states', ['state_hash'], unique=True)
    op.create_index(op.f('ix_bank_auth_states_user_id'), 'bank_auth_states', ['user_id'], unique=False)
    op.create_table('bank_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=150), nullable=True),
    sa.Column('provider_id', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONNECTED', 'EXPIRED', 'REVOKED', 'FAILED', name='bank_connection_status'), nullable=False),
    sa.Column('truelayer_connection_id', sa.String(length=150), nullable=True),
    sa.Column('access_token_encrypted', sa.String(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_connections_user_id'), 'bank_connections', ['user_id'], unique=False)
    op.create_table('bank_account_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_connection_id', sa.UUID(), nullable=False),
    sa.Column('external_account_id', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_connection_id'], ['bank_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_connection_id', 'external_account_id', name='uq_bank_account_snapshot_connection_external_id')
    )
    op.create_index(op.f('ix_bank_account_snapshots_bank_connection_id'), 'bank_account_snapshots', ['bank_connection_id'], unique=False)
    op.create_table('bank_transaction_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_connection_id', sa.UUID(), nullable=False),
    sa.Column('external_account_id', sa.String(length=150), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_connection_id'], ['bank_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_connection_id', 'external_transaction_id', name='uq_bank_transaction_snapshot_connection_external_id')
    )
    op.create_index(op.f('ix_bank_transaction_snapshots_bank_connection_id'), 'bank_transaction_snapshots', ['bank_connection_id'], unique=False)
    op.create_index('ix_bank_transaction_snapshots_connection_occurred_at', 'bank_transaction_snapshots', ['bank_connection_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_bank_transaction_snapshots_external_account_id'), 'bank_transaction_snapshots', ['external_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transaction_snapshots_external_account_id'), table_name='bank_transaction_snapshots')
    op.drop_index('ix_bank_transaction_snapshots_connection_occurred_at', table_name='bank_transaction_snapshots')
    op.drop_index(op.f('ix_bank_transaction_snapshots_bank_connection_id'), table_name='bank_transaction_snapshots')
    op.drop_table('bank_transaction_snapshots')
    op.drop_index(op.f('ix_bank_account_snapshots_bank_connection_id'), table_name='bank_account_snapshots')
    op.drop_table('bank_account_snapshots')
    op.drop_index(op.f('ix_bank_connections_user_id'), table_name='bank_connections')
    op.drop_table('bank_connections')
    sa.Enum(name='bank_connection_status').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_bank_auth_states_user_id'), table_name='bank_auth_states')
    op.drop_index(op.f('ix_bank_auth_states_state_hash'), table_name='bank_auth_states')
    op.drop_table('bank_auth_states')
    # ### end Alembic commands ###
