"use client";

import Image from "next/image";
import Link from "next/link";
import { useRef, useState, type ReactNode } from "react";
import { motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { ArrowDown, ArrowUpRight, Check, Coffee, Heart, Home, MapPin, Menu, MessageCircle, Moon, Plus, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import Logo from "@/components/ui/Logo";
import s from "./CoflowLanding.module.css";

function Reveal({ children, className = "" }: { children: ReactNode; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={false} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.12 }}><motion.div initial={false} whileInView={reduced ? {} : { y: [24, 0] }} viewport={{ once: true }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div></motion.div>;
}

const lifestyles = [
  { name: "Calma en casa", icon: Moon, title: "Tu casa, tu pausa.", text: "Descansar bien, tener tu espacio y compartir sin invadir. A veces, encajar es disfrutar del mismo silencio.", tags: ["Descanso temprano", "Espacio personal", "Ambiente tranquilo"], values: [90, 40, 85, 70, 95], label: "Un hogar donde bajar el ritmo", color: "#dbe8b9" },
  { name: "Vida compartida", icon: Coffee, title: "Hay sitio para un café más.", text: "Cocinar juntos, una charla improvisada y planes que empiezan en el salón. Tu gente también puede estar en casa.", tags: ["Planes en común", "Cocina compartida", "Puertas abiertas"], values: [65, 95, 60, 90, 70], label: "Un hogar lleno de pequeños planes", color: "#f1d0b4" },
  { name: "A mi aire", icon: Home, title: "Juntos. Con tu propio espacio.", text: "Horarios distintos, independencia y acuerdos claros. Compartir casa también es respetar la forma de vivir del otro.", tags: ["Independencia", "Rutinas flexibles", "Acuerdos claros"], values: [75, 55, 95, 55, 85], label: "Un hogar que respeta tu mundo", color: "#cadce7" },
];
const steps = [
  { title: "Primero, tú.", text: "Cuenta cómo vives: tus horarios, presupuesto y lo que necesitas para sentirte a gusto.", icon: Sparkles, detail: "Tu perfil de convivencia", chips: ["Tus rutinas", "Tu presupuesto", "Tus imprescindibles"] },
  { title: "Después, tu gente.", text: "Descubre personas y comunidades. Mira qué compartís antes de empezar una conversación.", icon: Users, detail: "Conexiones con contexto", chips: ["Personas", "Comunidades", "Preferencias en común"] },
  { title: "Y entonces, hogar.", text: "Hablad, conoced vuestras expectativas y decidid si queréis dar el siguiente paso.", icon: MessageCircle, detail: "Una decisión compartida", chips: ["Conversaciones", "Acuerdos", "Vuestro siguiente paso"] },
];
const faqs = [
  ["¿Qué es exactamente Coflow?", "Coflow es una plataforma para conocer personas compatibles con las que compartir piso y crear comunidades de convivencia. Puedes comparar hábitos, presupuesto y preferencias antes de decidir con quién vivir."],
  ["¿Necesito tener ya un piso?", "No. Puedes empezar por conocer personas y formar una comunidad. Si ya tienes una vivienda, puedes consultar el espacio para propietarios y descubrir cómo funciona."],
  ["¿Crear mi perfil es gratis?", "Sí. Puedes crear tu perfil gratis y contar cómo te gusta convivir para empezar a conocer personas y comunidades."],
  ["¿Dónde está disponible?", "El lanzamiento de Coflow está centrado en Málaga. Queremos construir una comunidad local útil, empezando por conectar a personas que buscan compartir casa en la misma ciudad."],
  ["¿Coflow garantiza que vayamos a encajar?", "No. Las preferencias aportan contexto, pero la decisión siempre es vuestra. Os animamos a hablar, conoceros y acordar los detalles de la convivencia antes de asumir compromisos."],
];

export default function CoflowLanding() {
  const [menu, setMenu] = useState(false);
  const [life, setLife] = useState(0);
  const [step, setStep] = useState(0);
  const hero = useRef<HTMLElement>(null);
  const reduced = useReducedMotion();
  const { scrollYProgress } = useScroll({ target: hero, offset: ["start start", "end start"] });
  const y = useTransform(scrollYProgress, [0, 1], [0, 100]);
  const current = lifestyles[life];
  const StepIcon = steps[step].icon;
  return <div className={s.landing}>
    <a href="#contenido" className={s.skip}>Saltar al contenido</a>
    <header className={s.header}>
      <Link href="/" className={s.brand} aria-label="Coflow, inicio"><Logo size="sm" /><span>coflow<span className={s.brandDot}>.</span></span></Link>
      <nav className={s.desktopNav} aria-label="Navegación principal"><a href="#como-funciona">Cómo funciona</a><a href="#tu-forma-de-vivir">Tu forma de vivir</a><Link href="/para-propietarios">Soy propietario <ArrowUpRight size={14}/></Link></nav>
      <div className={s.navActions}><Link className={s.login} href="/login">Entrar</Link><Link href="/register" className={s.buttonSmall}>Encuentra tu gente <ArrowUpRight size={16}/></Link><button className={s.menuButton} aria-expanded={menu} aria-controls="mobile-menu" aria-label={menu ? "Cerrar menú" : "Abrir menú"} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></div>
      {menu && <nav id="mobile-menu" className={s.mobileNav} aria-label="Navegación móvil"><a href="#como-funciona" onClick={() => setMenu(false)}>Cómo funciona</a><a href="#tu-forma-de-vivir" onClick={() => setMenu(false)}>Tu forma de vivir</a><Link href="/para-propietarios">Soy propietario</Link><Link href="/login">Entrar</Link></nav>}
    </header>
    <main id="contenido">
      <section className={s.hero} ref={hero}>
        <div className={s.heroCopy}><span className={s.eyebrow}><span className={s.liveDot}/> NUEVAS CONEXIONES, EN MÁLAGA</span><h1>Tu próxima casa<br/>empieza por<br/><span className={s.serif}>tu gente.</span><svg className={s.heroStar} viewBox="0 0 80 80" aria-hidden="true"><path d="M40 0v80M0 40h80M12 12l56 56M12 68l56-56" stroke="currentColor" strokeWidth="7"/></svg></h1><p>Un piso se encuentra.<br/>Sentirse en casa va de con quién lo compartes.</p><p className={s.heroDescription}>Conoce personas que encajan con tu forma de vivir.<br className={s.desktopBreak}/> Comparte mucho más que una dirección.</p><div className={s.heroButtons}><Link href="/register" className={s.button}>Encuentra tu gente <ArrowUpRight size={20}/></Link><a className={s.textLink} href="#como-funciona">Así funciona <ArrowDown size={16}/></a></div><div className={s.heroNote}><Check size={15}/> Crea tu perfil gratis <span/> Tú decides con quién conectar</div></div>
        <div className={s.heroVisual}><motion.div className={s.heroPhoto} style={{ y: reduced ? 0 : y }}><Image src="/images/owners-malaga-apartment-v2.png" alt="Salón luminoso con un sofá y un balcón abierto, un espacio para compartir" fill priority sizes="(max-width: 800px) 100vw, 52vw"/><div className={s.photoShade}/></motion.div><span className={s.photoLabel}><MapPin size={14}/> Málaga, nuestro punto de encuentro</span><div className={s.photoCaption}>Más que compartir piso.<br/><em>Compartir el mismo flow.</em></div><motion.div className={s.floatingCard} initial={false} animate={reduced ? {} : { y: [0, -8, 0] }} transition={{ repeat: Infinity, duration: 6, ease: "easeInOut" }}><div className={s.cardIcon}><Heart size={20}/></div><div><strong>Qué bien cuando encajas.</strong><span>Tu espacio. Tus rutinas. Tu gente.</span></div><span className={s.cardCheck}><Check size={15}/></span></motion.div><div className={s.photoIndex}>01 / EL PRINCIPIO DE ALGO BUENO</div></div>
      </section>
      <div className={s.valuesBar}><span>MENOS BUSCAR. MÁS ENCAJAR.</span><span><Users/> Personas antes que habitaciones</span><span><Heart/> Afinidad en el día a día</span><span><MessageCircle/> Conversaciones antes de decidir</span></div>
      <section className={`${s.section} ${s.manifesto}`}><Reveal><span className={s.eyebrow}>EL METRO CUADRADO MÁS IMPORTANTE ERES TÚ</span><h2>La luz importa.<br/>El barrio también.<br/><span className={s.faded}>Pero quien te pregunta</span><br/><span className={s.serif}>«¿qué tal tu día?»</span><br/>lo cambia todo.</h2><p>Por eso empezamos por las personas. Por cómo vivís,<br className={s.desktopBreak}/> lo que os importa y esas pequeñas cosas que hacen hogar.</p></Reveal><span className={s.manifestoMark} aria-hidden="true">co.</span></section>
      <section id="tu-forma-de-vivir" className={`${s.section} ${s.compatibility}`}>
        <Reveal><div className={s.sectionHeading}><div><span className={s.eyebrow}>01 / EL MISMO FLOW</span><h2>No es vivir igual.<br/>Es vivir <span className={s.serif}>bien juntos.</span></h2></div><p>Las pequeñas cosas hacen la gran diferencia.<br/>Explora distintas formas de sentirte en casa.</p></div></Reveal>
        <div className={s.experience}><div className={s.experienceCopy}><div className={s.lifeTabs} role="tablist" aria-label="Formas de convivir">{lifestyles.map((item, i) => <button key={item.name} id={`life-tab-${i}`} role="tab" aria-selected={life === i} aria-controls="life-panel" tabIndex={life === i ? 0 : -1} onKeyDown={(event) => { const keys = ["ArrowRight", "ArrowLeft", "Home", "End"]; if (!keys.includes(event.key)) return; event.preventDefault(); const next = event.key === "Home" ? 0 : event.key === "End" ? lifestyles.length - 1 : (i + (event.key === "ArrowRight" ? 1 : -1) + lifestyles.length) % lifestyles.length; setLife(next); document.getElementById(`life-tab-${next}`)?.focus(); }} onClick={() => setLife(i)} className={life === i ? s.activeTab : ""}><item.icon size={17}/>{item.name}</button>)}</div><div id="life-panel" role="tabpanel" aria-labelledby={`life-tab-${life}`} aria-live="polite"><motion.div key={life} initial={reduced ? false : { opacity: 1, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3 }}><h3>{current.title}</h3><p>{current.text}</p><div className={s.tags}>{current.tags.map(tag => <span key={tag}><Check size={13}/>{tag}</span>)}</div></motion.div></div><Link href="/register" className={s.textLink}>Encuentra tu forma de convivir <ArrowUpRight size={18}/></Link></div>
        <div className={s.radarPanel} style={{ background: current.color }}><div className={s.radarTop}><span>EL ADN DE TU CONVIVENCIA</span><Sparkles size={19}/></div><svg viewBox="0 0 360 310" className={s.radar} role="img" aria-label={`Ejemplo ilustrativo: ${current.label}`}>
          {[0.25, 0.5, 0.75, 1].map(scale => <polygon key={scale} points={Array.from({ length: 5 }, (_, i) => { const a = (i * 72 - 90) * Math.PI / 180; return `${180 + Math.cos(a) * 100 * scale},${150 + Math.sin(a) * 100 * scale}`; }).join(" ")} fill="none" stroke="#173c3226"/>)}
          <motion.polygon initial={false} animate={{ points: current.values.map((v, i) => { const a = (i * 72 - 90) * Math.PI / 180; return `${180 + Math.cos(a) * v},${150 + Math.sin(a) * v}`; }).join(" ") }} transition={{ duration: reduced ? 0 : 0.55 }} fill="#244c3440" stroke="#244c34" strokeWidth="2"/>
          {["Descanso", "Vida social", "Flexibilidad", "Planes", "Espacio"].map((label, i) => { const a = (i * 72 - 90) * Math.PI / 180; return <text key={label} x={180 + Math.cos(a) * 140} y={150 + Math.sin(a) * 128} textAnchor="middle" dominantBaseline="middle" fill="#244335" fontSize="12">{label}</text>; })}</svg><strong>{current.label}</strong><small>Demo ilustrativa · Tu perfil será único</small></div></div>
      </section>
      <section id="como-funciona" className={`${s.section} ${s.how}`}><Reveal><span className={s.eyebrow}>02 / ASÍ DE NATURAL</span><h2>De «busco piso»<br/>a <span className={s.serif}>«aquí encajo».</span></h2></Reveal><div className={s.stepsLayout}><div className={s.steps}>{steps.map((item, i) => <button key={item.title} className={`${s.step} ${step === i ? s.selectedStep : ""}`} onClick={() => setStep(i)} aria-pressed={step === i} aria-controls="step-preview"><span>0{i + 1}</span><div><h3>{item.title}</h3><p>{item.text}</p></div><ArrowUpRight size={22}/></button>)}</div><div id="step-preview" className={s.stepPreview} aria-live="polite"><div className={s.previewWindow}><div className={s.windowTop}><span/><span/><span/><small>tu próximo capítulo</small></div><motion.div key={step} initial={reduced ? false : { opacity: 1, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }} className={s.previewContent}><div className={s.previewIcon}><StepIcon size={37} strokeWidth={1.3}/></div><span className={s.eyebrow}>PASO 0{step + 1}</span><h3>{steps[step].detail}</h3>{steps[step].chips.map((chip, i) => <div className={s.previewRow} key={chip}><span>0{i + 1}</span>{chip}<Check size={16}/></div>)}</motion.div></div><span className={s.previewFoot}>A tu ritmo. Con toda la información.</span></div></div></section>
      <section className={`${s.section} ${s.trust}`}><Reveal><div className={s.sectionHeading}><div><span className={s.eyebrow}>03 / CON LAS COSAS CLARAS</span><h2>La confianza no se promete.<br/><span className={s.serif}>Se construye.</span></h2></div><p>Compartir casa es una decisión importante.<br/>Queremos que puedas tomarla con contexto.</p></div></Reveal><div className={s.trustGrid}>{[{ icon: Users, title: "Más contexto. Menos incógnitas.", text: "Hábitos, horarios y preferencias de convivencia para conocer lo que una foto no cuenta." }, { icon: MessageCircle, title: "Primero, una conversación.", text: "Hablad de lo que os importa antes de dar el siguiente paso. Sin saltarse lo esencial." }, { icon: ShieldCheck, title: "La decisión siempre es tuya.", text: "Tú eliges con quién conectar. Consulta nuestras normas y las opciones de privacidad." }].map((item, i) => <Reveal key={item.title}><article className={s.trustCard}><span className={s.trustNumber}>0{i + 1}</span><item.icon size={28} strokeWidth={1.3}/><h3>{item.title}</h3><p>{item.text}</p></article></Reveal>)}</div><Link href="/legal/normas-comunidad" className={s.textLink}>Conoce nuestras normas de comunidad <ArrowUpRight size={16}/></Link></section>
      <section className={s.city}><Image src="/images/cities/malaga.webp" alt="Vista de Málaga, ciudad de lanzamiento de Coflow" fill sizes="100vw"/><div className={s.cityOverlay}/><div className={s.cityContent}><span className={s.eyebrow}><MapPin size={15}/> EMPEZAMOS CERCA</span><Reveal><h2>Málaga.<br/>Mucho más que<br/><span className={s.serif}>un lugar al sol.</span></h2><p>Una ciudad para empezar de nuevo.<br/>Y personas con las que sentirte en casa.</p><Link href="/companeros-de-piso/malaga" className={`${s.button} ${s.lightButton}`}>Encuentra tu gente en Málaga <ArrowUpRight size={19}/></Link></Reveal></div><span className={s.cityCoordinates}>36°43′ N &nbsp; 4°25′ O<br/>NUESTRO PRIMER CAPÍTULO</span></section>
      <section className={`${s.section} ${s.faq}`}><div><span className={s.eyebrow}>SIN QUEDARTE CON DUDAS</span><h2>Hablemos<br/><span className={s.serif}>claro.</span></h2><p>Lo que quizá te estás preguntando.</p></div><div className={s.faqList}>{faqs.map(([q, a]) => <details key={q}><summary>{q}<Plus size={20}/></summary><p>{a}</p></details>)}</div></section>
      <section className={s.finalCta}><span className={s.eyebrow}>TU SIGUIENTE CAPÍTULO EMPIEZA AQUÍ</span><Reveal><h2>Hay gente con<br/><span className={s.serif}>tu mismo flow.</span></h2><p>Solo falta que os encontréis.</p><Link href="/register" className={`${s.button} ${s.lightButton}`}>Quiero encontrar mi gente <ArrowUpRight size={21}/></Link><small>Tu perfil es gratis. El primer paso es tuyo.</small></Reveal><span className={s.ctaOrbit} aria-hidden="true"/></section>
    </main>
    <footer className={s.footer}><div className={s.footerTop}><Link href="/" className={s.brand}><Logo size="sm"/><span>coflow.</span></Link><p>Compartir casa. Encontrar tu gente.</p><Link href="/para-propietarios">¿Tienes una vivienda? <ArrowUpRight size={16}/></Link></div><div className={s.footerBottom}><span>© {new Date().getFullYear()} Coflow · Hecho para convivir mejor.</span><nav aria-label="Información legal"><Link href="/legal/privacidad">Privacidad</Link><Link href="/legal/terminos">Términos</Link><Link href="/legal/cookies">Cookies</Link><Link href="/legal/aviso-legal">Aviso legal</Link></nav></div></footer>
  </div>;
}
